### ISSUE TITLE
Correct data not showing on display

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/rise-financial#24]
## Issue
When using the financial component on an authorized display, the component still returns the dummy data e.g. lastChange showing as 1.234

## Steps to Replicate
1. Set up a list of financial instruments and the financial component and add this to a new presentation.
2. Add the presentation to an authorized display and the dummy data is still visible.

## Expected Results
The dummy data seen on the desktop version should be replaced by live data when shown on an authorized display

**Comment by stulees** [comment]
@pcsandford There are no logs today that have a display id value which indicates that Rise Cache was not running when you were testing. Do you have a link to the presentation for the above and/or schedule so I can try adding my display? Thanks

**Comment by stulees** [comment]
@pcsandford Actually, disregard above regarding Rise Cache. A link to your presentation would still be good though, thanks.

**Comment by pcsandford** [comment]
@stulees here is the link to the presentation, thanks! https://apps.risevision.com/editor/workspace/c496d6e0-a985-4aa2-9d2a-ed4445086408/?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

**Comment by stulees** [comment]
@pcsandford Thanks, had you ran this on a display or in preview?

**Comment by pcsandford** [comment]
@stulees on a display - @sheadarlison is also running it on a brightlane display which I think is also authorized. Thanks!

**Comment by stulees** [comment]
@pcsandford This issue is fixed with latest release of the component. The component will work correctly regardless of protocol (https or http) that your page is using. When updating your content to use latest release, be sure to overwrite your bower components directory with latest dependencies, specifically rise-logger and rise-data as they have new releases that were involved in the fix. 

When you've validated can you close this issue, cheers.

**Comment by pcsandford** [comment]
@stulees awesome, thanks! I should be able to validate this later today on the next marketwall build. @sheadarlison FYI

Thanks!
